
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/team01-m23-10am-4
owner: ucsb-cs156-m23
repo_name: team01-m23-10am-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjQxMTY1MjA0","is_bot":false,"login":"dscpsyl","name":"SimYouLater"},"headRefName":"David-HomeController","number":21,"title":"ADD: homecontroller","url":"https://github.com/ucsb-cs156-m23/team01-m23-10am-4/pull/21"},{"author":{"id":"MDQ6VXNlcjQxMTY1MjA0","is_bot":false,"login":"dscpsyl","name":"SimYouLater"},"headRefName":"David-UniversityQueryController","number":19,"title":"ADD: university controller","url":"https://github.com/ucsb-cs156-m23/team01-m23-10am-4/pull/19"},{"author":{"id":"MDQ6VXNlcjQxMTY1MjA0","is_bot":false,"login":"dscpsyl","name":"SimYouLater"},"headRefName":"David-UniversityQueryService","number":18,"title":"ADD: university service endpoint","url":"https://github.com/ucsb-cs156-m23/team01-m23-10am-4/pull/18"},{"author":{"id":"MDQ6VXNlcjE4Njg1MDcy","is_bot":false,"login":"iain801","name":"Iain Weissburg"},"headRefName":"Iain-Tides","number":17,"title":"iw - added service and tests for tides","url":"https://github.com/ucsb-cs156-m23/team01-m23-10am-4/pull/17"}]
